/// Flutter icons Animals
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Animals
///      fonts:
///       - asset: fonts/Animals.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Animals {
  Animals._();

  static const _kFontFam = 'Animals';
  static const String? _kFontPkg = null;

  static const IconData spider = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ant = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
